{
    'name': 'HMS',
    'author': 'Khalid Sadoun',
    'website': '',
    'description': 'Hospital Management System',
    'version': '1.0',
    'depends': ['base', 'contacts'],
    'data': [
        'security/hms_security.xml',
        'security/ir.model.access.csv',
        'views/department_views.xml',
        'views/doctor_views.xml',
        'views/patient_views.xml',
        'views/res_partner_views.xml',
        'report/patient_report.xml',
        'report/patient_report_template.xml',
    ],
    'installable': True,
    'application': True, 
}